[BUILD] Tag Pulsar related work as unstable
Failed in 4 builds out of 7.

```
com.github.fge.lambdas.ThrownByLambdaException: org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Tenant does not exist
Caused by: org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Tenant does not exist
Caused by: org.apache.pulsar.shade.javax.ws.rs.NotFoundException: HTTP 404 Tenant does not exist
```