JAMES-3737 Upon IMAP deselect registration.get() can be null
This happens for instance when an error happens before the session is
fully selected eg upon IMAP error.

```
java.lang.NullPointerException: Cannot invoke "org.apache.james.events.Registration.unregister()" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null
at org.apache.james.imap.processor.base.SelectedMailboxImpl.deselect(SelectedMailboxImpl.java:196)
at org.apache.james.imapserver.netty.NettyImapSession.closeMailbox(NettyImapSession.java:153)
at org.apache.james.imapserver.netty.NettyImapSession.selected(NettyImapSession.java:127)
at org.apache.james.imap.processor.AbstractSelectionProcessor.selectMailbox(AbstractSelectionProcessor.java:409)
at org.apache.james.imap.processor.AbstractSelectionProcessor.lambda$selectMailbox$20(AbstractSelectionProcessor.java:383)
```