[BUILD] Fully drop glowroot
05:46:42,855 [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.2:buildTar (default) on project james-server-jpa-app: <extraDirectories><paths> contain "from" directory that doesn't exist locally: /home/jenkins/jenkins-agent/workspace/james_ApacheJames_PR-2609/server/apps/jpa-app/target/glowroot -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.2:buildTar (default) on project james-server-jpa-app: <extraDirectories><paths> contain "from" directory that doesn't exist locally: /home/jenkins/jenkins-agent/workspace/james_ApacheJames_PR-2609/server/apps/jpa-app/target/glowroot
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)

Following the work: https://github.com/apache/james-project/commit/82523f59f3a00ac797a1a85906ecd3135fd434df.

I do not know why the build has not failed before. But it is now, and it needs to be fixed.