JAMES-3605 TerminationReconnectionHandler should not create the termination queue upon reconnection
Otherwise error:
```
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'x-queue-version' for queue 'terminationSubscriber291d56fc-1e2d-4fb3-a455-bad297263f43' in vhost '/': received none but current is the value '2' of type 'signedint', class-id=50, method-id=10)
```

And cause the remaining reconnection handlers to fail.