JAMES-3737 ImapRequestFrameDecoder: remove buggy code
Unneeded, the cumulation cary over when disabling framing do not need it.

Buggy: next handler do not expect a ByteBuf

java.lang.ClassCastException: class io.netty.buffer.PooledDuplicatedByteBuf cannot be cast to class org.apache.james.imap.api.ImapMessage (io.netty.buffer.PooledDuplicatedByteBuf and org.apache.james.imap.api.ImapMessage are in unnamed module of loader 'app')