[ENHANCEMENT] Prevent verbose logs when WS client disconnect during handshake
Solves this:

java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.netty.util.Attribute.get()" is null
	at reactor.netty.Connection.isPersistent(Connection.java:248)
	at reactor.netty.channel.ChannelOperations.isPersistent(ChannelOperations.java:607)
	at reactor.netty.ReactorNetty.addHandlerBeforeReactorEndHandlers(ReactorNetty.java:390)
	at reactor.netty.Connection.addHandlerLast(Connection.java:165)
	at reactor.netty.http.websocket.WebsocketInbound.lambda$aggregateFrames$0(WebsocketInbound.java:86)
	at reactor.netty.http.server.HttpServerOperations.withConnection(HttpServerOperations.java:250)
	at reactor.netty.http.server.HttpServerOperations.withConnection(HttpServerOperations.java:124)
	at reactor.netty.http.websocket.WebsocketInbound.aggregateFrames(WebsocketInbound.java:86)
	at reactor.netty.http.websocket.WebsocketInbound.aggregateFrames(WebsocketInbound.java:74)
	at org.apache.james.jmap.routes.WebSocketRoutes.handleWebSocketConnection(WebSocketRoutes.scala:119)