JAMES-3827 Support From fields without domain parts in the email address
```
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "s" is nul
  at org.apache.james.mailbox.elasticsearch.json.EMailer.removeTopDomain(EMailer.java:42)
  at org.apache.james.mailbox.elasticsearch.json.EMailer.<init>(EMailer.java:38)
  at org.apache.james.mailbox.elasticsearch.json.HeaderCollection$Builder.lambda$manageAddressField$0(HeaderCollection.java:145)
```